modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "HuHoBot"
authors = "huohuas001"
description = '''
HuHoBot - A Minecraft bot integration mod for server management.
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version}]"
ordering = "AFTER"
side = "BOTH"
